# Generated by Django 5.1.6 on 2026-08-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlackLLMKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_team_id", models.CharField(max_length=32)),
                ("slack_user_id", models.CharField(max_length=32)),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        max_length=16,
                    ),
                ),
                ("encrypted_api_key", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slack_team_id", "slack_user_id"),
                        name="unique_key_per_slack_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SlackQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_team_id", models.CharField(max_length=32)),
                ("slack_user_id", models.CharField(max_length=32)),
                ("channel_id", models.CharField(max_length=32)),
                ("thread_ts", models.CharField(max_length=32)),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                        max_length=16,
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="ok", max_length=32)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "slack queries",
                "indexes": [
                    models.Index(
                        fields=["channel_id", "thread_ts", "created_at"],
                        name="slackquery_thread_idx",
                    )
                ],
            },
        ),
    ]
