# Generated by Django 6.0.3 on 2026-03-21 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_allow_contact_passwordresettoken_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=500)),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "session_key",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "path"],
                        name="accounts_pa_timesta_e4251f_idx",
                    ),
                    models.Index(
                        fields=["timestamp", "ip_hash"],
                        name="accounts_pa_timesta_9be370_idx",
                    ),
                ],
            },
        ),
    ]
