# Generated by Django 6.0.3 on 2026-04-11 14:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_homepage_layout"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("visited_at", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-visited_at"],
            },
        ),
        migrations.CreateModel(
            name="RevisitSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("next_revisit", models.DateField()),
                ("recurrence_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "share_token",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisit_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_revisit"],
            },
        ),
        migrations.RenameModel(
            old_name="SavedComparison",
            new_name="SavedList",
        ),
        migrations.AddIndex(
            model_name="companyvisit",
            index=models.Index(
                fields=["user", "-visited_at"], name="accounts_co_user_id_17a748_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyvisit",
            unique_together={("user", "ticker", "visited_at")},
        ),
        migrations.AlterUniqueTogether(
            name="revisitschedule",
            unique_together={("user", "ticker")},
        ),
    ]
