# Generated by Django 5.1.6 on 2026-04-16 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_revisitschedule_dismissed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("indicator", models.CharField(max_length=40)),
                (
                    "comparison",
                    models.CharField(
                        choices=[
                            ("lte", "Less than or equal to"),
                            ("gte", "Greater than or equal to"),
                        ],
                        max_length=3,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=6, max_digits=20)),
                ("active", models.BooleanField(default=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "ticker"], name="accounts_in_user_id_9c434a_idx"
                    ),
                    models.Index(
                        fields=["active"], name="accounts_in_active_ac9da3_idx"
                    ),
                ],
                "unique_together": {("user", "ticker", "indicator", "comparison")},
            },
        ),
    ]
