# Generated by Django 5.1.6 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_savedscreenerfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("pt", "pt"),
                    ("en", "en"),
                    ("es", "es"),
                    ("zh", "zh"),
                    ("fr", "fr"),
                    ("de", "de"),
                    ("it", "it"),
                ],
                default="en",
                max_length=5,
            ),
        ),
    ]
