# Generated by Django 6.0.3 on 2026-04-23 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("indicator", models.CharField(max_length=40)),
                (
                    "comparison",
                    models.CharField(
                        choices=[
                            ("lte", "Less than or equal to"),
                            ("gte", "Greater than or equal to"),
                        ],
                        max_length=3,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "indicator_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_al_user_id_c84382_idx",
                    )
                ],
            },
        ),
    ]
