# Generated by Django 5.1.6 on 2026-03-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_igpmindex_delete_ipcaindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPCAIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "annual_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="12-month accumulated IPCA rate (%)",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="IGPMIndex",
        ),
    ]
