# Generated by Django 6.0.3 on 2026-03-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_quarterlycashflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                ("end_date", models.DateField()),
                (
                    "total_debt",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Dívida bruta (short + long term debt)",
                        null=True,
                    ),
                ),
                (
                    "total_liabilities",
                    models.BigIntegerField(
                        blank=True, help_text="Passivo total", null=True
                    ),
                ),
                (
                    "stockholders_equity",
                    models.BigIntegerField(
                        blank=True, help_text="Patrimônio líquido", null=True
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-end_date"],
                "unique_together": {("ticker", "end_date")},
            },
        ),
    ]
