# Generated by Django 6.0.3 on 2026-03-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_add_balance_sheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("sector", models.CharField(blank=True, default="", max_length=100)),
                ("type", models.CharField(blank=True, default="", max_length=50)),
                ("logo", models.URLField(blank=True, default="", max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
    ]
