# Generated by Django 6.0.3 on 2026-03-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0006_add_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="total_lease",
            field=models.BigIntegerField(
                blank=True, help_text="Arrendamentos (leasing CP + LP)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="balancesheet",
            name="total_debt",
            field=models.BigIntegerField(
                blank=True,
                help_text="Dívida bruta (empréstimos + arrendamentos)",
                null=True,
            ),
        ),
    ]
