# Generated by Django 6.0.3 on 2026-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0007_add_total_lease"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="current_assets",
            field=models.BigIntegerField(
                blank=True, help_text="Ativo circulante", null=True
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="current_liabilities",
            field=models.BigIntegerField(
                blank=True, help_text="Passivo circulante", null=True
            ),
        ),
        migrations.AddField(
            model_name="quarterlycashflow",
            name="dividends_paid",
            field=models.BigIntegerField(
                blank=True,
                help_text="Dividendos pagos (dividendsPaid from BRAPI, negative value)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyearnings",
            name="revenue",
            field=models.BigIntegerField(
                blank=True,
                help_text="Receita líquida (totalRevenue from BRAPI)",
                null=True,
            ),
        ),
    ]
