# Generated by Django 6.0.3 on 2026-03-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0009_force_resync_balance_sheets"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
