# Generated by Django 6.0.3 on 2026-03-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0010_add_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                (
                    "content",
                    models.TextField(
                        help_text="Analysis text in Portuguese (markdown format)"
                    ),
                ),
                (
                    "data_quarter",
                    models.CharField(
                        help_text="Quarter covered by this analysis, e.g. '2025-Q4'",
                        max_length=7,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "company analyses",
                "ordering": ["-generated_at"],
            },
        ),
    ]
