# Generated by Django 6.0.3 on 2026-04-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0011_companyanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="USCPIIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "annual_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Year-over-year CPI rate (%) for the US",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
