# Generated by Django 6.0.3 on 2026-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0012_add_uscpi_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="market_cap",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
