# Generated by Django 5.1.6 on 2026-04-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0015_resync_balance_sheets_for_debt_fix"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10, unique=True)),
                (
                    "pe10",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "pfcf10",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "peg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "pfcf_peg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "debt_to_equity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "debt_ex_lease_to_equity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "liabilities_to_equity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "current_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "debt_to_avg_earnings",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "debt_to_avg_fcf",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ticker"],
                "indexes": [
                    models.Index(fields=["pe10"], name="quotes_indi_pe10_3b4ec8_idx"),
                    models.Index(
                        fields=["pfcf10"], name="quotes_indi_pfcf10_d1f052_idx"
                    ),
                    models.Index(
                        fields=["market_cap"], name="quotes_indi_market__8ff638_idx"
                    ),
                ],
            },
        ),
    ]
