# Generated by Django 5.1.6 on 2026-04-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0016_indicatorsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="aliases",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Newline-separated former or alternate names used for search (e.g. 'General Electric' for GE after the 2024 rebrand).",
            ),
        ),
    ]
