# Generated by Django 5.1.6 on 2026-05-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0018_seed_ticker_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarterlycashflow",
            name="free_cash_flow",
            field=models.BigIntegerField(
                blank=True,
                help_text="Provider-reported FCF (FMP `freeCashFlow` ≈ OCF − CapEx). None when the provider does not expose it (e.g. BRAPI).",
                null=True,
            ),
        ),
    ]
