# Generated by Django 5.1.6 on 2026-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0019_add_free_cash_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="reported_currency",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO 4217 code of the currency the company files financial statements in (BRL for B3 tickers, USD/EUR/JPY/etc. for FMP). Empty until the first income-statement sync populates it for FMP-sourced tickers. Used to translate market cap into the statement currency before computing PE10/PFCF10/etc.",
                max_length=3,
            ),
        ),
    ]
