# Generated by Django 5.1.6 on 2026-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0020_add_ticker_reported_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryCPIIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(db_index=True, max_length=3)),
                ("date", models.DateField()),
                (
                    "annual_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Year-over-year CPI rate (%) for the corresponding currency.",
                        max_digits=10,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["currency", "-date"],
                        name="quotes_coun_currenc_818762_idx",
                    )
                ],
                "unique_together": {("currency", "date")},
            },
        ),
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("base_currency", models.CharField(max_length=3)),
                ("quote_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=20)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["base_currency", "quote_currency", "-date"],
                        name="quotes_fxra_base_cu_f51583_idx",
                    )
                ],
                "unique_together": {("date", "base_currency", "quote_currency")},
            },
        ),
    ]
