# Generated by Django 6.0.3 on 2026-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0021_add_fx_and_country_cpi"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="country",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISO 3166-1 alpha-2 country code of the company's incorporation (e.g. BR for Brazilian B3 listings, US for US-domiciled, TW for Taiwan Semiconductor ADR). Backfilled from FMP's company profile for non-Brazilian tickers; deterministically set to BR for anything matching the Brazilian symbol pattern.",
                max_length=2,
            ),
        ),
    ]
