# Generated by Django 6.0.3 on 2026-05-09 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0023_seed_brazilian_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lookuplog",
            index=models.Index(
                fields=["ticker", "timestamp"], name="quotes_look_ticker_7b73ac_idx"
            ),
        ),
    ]
