# Generated by Django 5.1.6 on 2026-05-17 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0024_add_lookup_log_ticker_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lookuplog",
            name="ip_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="lookuplog",
            index=models.Index(
                fields=["ip_hash", "timestamp"], name="quotes_look_ip_hash_71104c_idx"
            ),
        ),
    ]
