# Generated by Django 5.1.6 on 2026-08-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0025_lookuplog_ip_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CvmArchiveBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(db_index=True)),
                (
                    "last_modified",
                    models.DateTimeField(
                        help_text="Last-Modified reported for the archive, i.e. when CVM built it"
                    ),
                ),
                ("etag", models.CharField(blank=True, max_length=128)),
                (
                    "filing_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Rows in the filing index for this build",
                        null=True,
                    ),
                ),
                ("first_observed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_modified"],
                "unique_together": {("year", "last_modified")},
            },
        ),
        migrations.CreateModel(
            name="CvmFiling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cvm_code", models.CharField(db_index=True, max_length=10)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("cnpj", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "reference_date",
                    models.DateField(
                        db_index=True,
                        help_text="DT_REFER — the quarter the filing reports on",
                    ),
                ),
                (
                    "filed_at",
                    models.DateField(
                        blank=True,
                        help_text="DT_RECEB — when CVM received the filing",
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="VERSAO — a restatement is a new version, and a new row",
                    ),
                ),
                ("document_id", models.CharField(blank=True, max_length=20)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "first_seen_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filings",
                        to="quotes.cvmarchivebuild",
                    ),
                ),
            ],
            options={
                "ordering": ["-filed_at", "cvm_code"],
                "indexes": [
                    models.Index(
                        fields=["reference_date", "filed_at"],
                        name="quotes_cvmf_referen_0a8d3e_idx",
                    )
                ],
                "unique_together": {("cvm_code", "reference_date", "version")},
            },
        ),
    ]
