# Generated by Django 5.1.6 on 2026-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0026_cvmarchivebuild_cvmfiling"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="cnpj",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CNPJ of the filing entity, as CVM renders it.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticker",
            name="cvm_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="CD_CVM, the code every CVM filing is keyed by. Brazilian tickers only; CVM publishes nothing for the rest of the universe. Stored here rather than in code so a wrong mapping is correctable without a deploy.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticker",
            name="cvm_match_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ticker", "Published trading code (FCA)"),
                    ("root", "Ticker root shared with a published code"),
                    ("name", "Normalised company name"),
                    ("manual", "Set by hand"),
                ],
                default="",
                help_text="Which evidence produced cvm_code. 'manual' is never overwritten by the automated pass, and is what a disputed figure is traced back through.",
                max_length=20,
            ),
        ),
    ]
