# Generated by Django 5.1.6 on 2026-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0027_ticker_cnpj_ticker_cvm_code_ticker_cvm_match_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("brapi", "BRAPI"),
                    ("fmp", "Financial Modeling Prep"),
                    ("cvm", "CVM open data"),
                    ("", "Unrecorded (written before provenance was tracked)"),
                ],
                db_index=True,
                default="",
                help_text="Which provider last wrote this row.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quarterlycashflow",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("brapi", "BRAPI"),
                    ("fmp", "Financial Modeling Prep"),
                    ("cvm", "CVM open data"),
                    ("", "Unrecorded (written before provenance was tracked)"),
                ],
                db_index=True,
                default="",
                help_text="Which provider last wrote this row.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyearnings",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("brapi", "BRAPI"),
                    ("fmp", "Financial Modeling Prep"),
                    ("cvm", "CVM open data"),
                    ("", "Unrecorded (written before provenance was tracked)"),
                ],
                db_index=True,
                default="",
                help_text="Which provider last wrote this row.",
                max_length=10,
            ),
        ),
    ]
