# Generated by Django 5.1.6 on 2026-08-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0028_statement_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="filed_at",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="DT_RECEB of the filing this row came from (CVM-sourced rows).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlycashflow",
            name="filed_at",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="DT_RECEB of the filing this row came from (CVM-sourced rows).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyearnings",
            name="filed_at",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="DT_RECEB of the filing this row came from (CVM-sourced rows).",
                null=True,
            ),
        ),
    ]
