# Generated by Django 5.1.6 on 2026-08-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0030_backfill_statement_filed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe1",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe11",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe12",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe13",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe14",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe15",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe2",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe3",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe4",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe5",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe6",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe7",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe8",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe9",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="pe_years_available",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
