# Generated by Django 5.1.6 on 2026-08-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0032_add_ticker_name_trigram_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexNowSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20, unique=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
    ]
