# Generated by Django 5.1.6 on 2026-08-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0033_indexnow_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="fiscal_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Fiscal year this period belongs to. Null when the provider does not report one.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlycashflow",
            name="fiscal_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Fiscal year this period belongs to. Null when the provider does not report one.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quarterlyearnings",
            name="fiscal_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Fiscal year this period belongs to. Null when the provider does not report one.",
                null=True,
            ),
        ),
    ]
