# Generated by Django 5.1.6 on 2026-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0034_balancesheet_fiscal_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_1",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_10",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_11",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_12",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_13",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_14",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_15",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_2",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_3",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_4",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_5",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_6",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_7",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_8",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_earnings_9",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_1",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_10",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_11",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_12",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_13",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_14",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_15",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_2",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_3",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_4",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_5",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_6",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_7",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_8",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="indicatorsnapshot",
            name="debt_to_avg_fcf_9",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
    ]
