# Generated by Django 5.1.6 on 2026-09-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0035_indicatorsnapshot_debt_coverage_windows"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderUsageDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("endpoint", models.CharField(max_length=120)),
                ("call_count", models.BigIntegerField(default=0)),
                ("bytes_downloaded", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["-date", "provider", "endpoint"],
                "indexes": [
                    models.Index(
                        fields=["provider", "-date"],
                        name="quotes_prov_provide_4d8fdb_idx",
                    )
                ],
                "unique_together": {("provider", "date", "endpoint")},
            },
        ),
    ]
