# Generated by Django 5.1.6 on 2026-09-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0036_providerusageday"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyClosePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("close", models.DecimalField(decimal_places=6, max_digits=20)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ticker", "date"],
                "indexes": [
                    models.Index(
                        fields=["ticker", "-date"], name="quotes_dail_ticker_b10ecc_idx"
                    )
                ],
                "unique_together": {("ticker", "date")},
            },
        ),
    ]
