# Generated by Django 5.1.6 on 2026-09-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0037_dailycloseprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="statements_last_attempted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the weekly refresh last asked the provider for this company's statements, whatever came back. 1,848 companies in the universe have no statements at all, and asking again every week costs 0.74 GB to re-confirm absence; see quotes.statement_refresh.",
                null=True,
            ),
        ),
    ]
