# Generated by Django 5.1.6 on 2026-09-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0038_ticker_statements_last_attempted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMarketCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("market_cap", models.BigIntegerField()),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ticker", "date"],
                "indexes": [
                    models.Index(
                        fields=["ticker", "-date"], name="quotes_dail_ticker_5c1309_idx"
                    )
                ],
                "unique_together": {("ticker", "date")},
            },
        ),
    ]
