from django.urls import path

from .views import (
    AdminDashboardView,
    AdminTopPagesView,
    ChangeEmailView,
    ChangePasswordView,
    DeleteAccountView,
    DismissAllRemindersView,
    DismissReminderView,
    FavoriteDetailView,
    FavoriteListView,
    FeedbackView,
    ForgotPasswordView,
    GoogleAuthView,
    HomepageLayoutView,
    IndicatorAlertDetailView,
    IndicatorAlertListView,
    LoginView,
    LogoutView,
    MarkVisitedView,
    MeView,
    PendingRemindersView,
    QuotaView,
    RemindersListView,
    ResetPasswordView,
    ReorderListsView,
    ResendVerificationView,
    RevisitScheduleDetailView,
    RevisitScheduleListView,
    SavedListDetailView,
    SavedListListView,
    SavedScreenerFilterDetailView,
    SavedScreenerFilterListView,
    SharedVisitsView,
    TrackPageView,
    SharedListView,
    SignupView,
    UpdatePreferencesView,
    VerifyEmailView,
    VisitDetailView,
    VisitListView,
)

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("me/", MeView.as_view(), name="me"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("change-email/", ChangeEmailView.as_view(), name="change-email"),
    path("preferences/", UpdatePreferencesView.as_view(), name="preferences"),
    path("delete-account/", DeleteAccountView.as_view(), name="delete-account"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("reset-password/", ResetPasswordView.as_view(), name="reset-password"),
    path("google/", GoogleAuthView.as_view(), name="google-auth"),
    path("quota/", QuotaView.as_view(), name="quota"),
    path("favorites/", FavoriteListView.as_view(), name="favorite-list"),
    path("favorites/<str:ticker>/", FavoriteDetailView.as_view(), name="favorite-detail"),
    path("visits/mark/", MarkVisitedView.as_view(), name="mark-visited"),
    path("visits/", VisitListView.as_view(), name="visit-list"),
    path("visits/schedules/", RevisitScheduleListView.as_view(), name="revisit-schedule-list"),
    path("visits/schedules/<int:pk>/", RevisitScheduleDetailView.as_view(), name="revisit-schedule-detail"),
    path("visits/shared/<str:token>/", SharedVisitsView.as_view(), name="shared-visits"),
    path("visits/reminders/", PendingRemindersView.as_view(), name="pending-reminders"),
    path("visits/reminders/list/", RemindersListView.as_view(), name="reminders-list"),
    path("visits/reminders/dismiss-all/", DismissAllRemindersView.as_view(), name="dismiss-all-reminders"),
    path("visits/reminders/<int:pk>/dismiss/", DismissReminderView.as_view(), name="dismiss-reminder"),
    path("visits/<int:pk>/", VisitDetailView.as_view(), name="visit-detail"),
    path("lists/", SavedListListView.as_view(), name="list-list"),
    path("lists/<int:pk>/", SavedListDetailView.as_view(), name="list-detail"),
    path("lists/reorder/", ReorderListsView.as_view(), name="list-reorder"),
    path("lists/shared/<str:token>/", SharedListView.as_view(), name="shared-list"),
    path("screener-filters/", SavedScreenerFilterListView.as_view(), name="screener-filter-list"),
    path("screener-filters/<int:pk>/", SavedScreenerFilterDetailView.as_view(), name="screener-filter-detail"),
    path("verify-email/", VerifyEmailView.as_view(), name="verify-email"),
    path("resend-verification/", ResendVerificationView.as_view(), name="resend-verification"),
    path("track/", TrackPageView.as_view(), name="track-page-view"),
    path("homepage-layout/", HomepageLayoutView.as_view(), name="homepage-layout"),
    path("feedback/", FeedbackView.as_view(), name="feedback"),
    path("admin/dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin/top-pages/", AdminTopPagesView.as_view(), name="admin-top-pages"),
    path("alerts/", IndicatorAlertListView.as_view(), name="indicator-alert-list"),
    path("alerts/<int:pk>/", IndicatorAlertDetailView.as_view(), name="indicator-alert-detail"),
]
