baseURL = "https://blog.sponda.capital/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Sponda"
enableRobotsTXT = true
enableGitInfo = false
pagination.pagerSize = 50

[taxonomies]
  tag = "tags"
  category = "categories"

[permalinks]
  posts = "/:slug/"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3

[params]
  description = "Notas sobre investimento em ações brasileiras."
  author = "Sponda"
  mainSiteURL = "https://sponda.capital"
