server {
    listen 80;
    server_name gustavosaiani.art.br www.gustavosaiani.art.br;
    return 301 https://gustavosaiani.art.br$request_uri;
}

server {
    listen 443 ssl;
    server_name gustavosaiani.art.br www.gustavosaiani.art.br;

    root /var/www/gustavosaiani.art.br/public_html;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/gustavosaiani.art.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gustavosaiani.art.br/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_log /var/log/nginx/gustavosaiani.art.br-error.log;
}
