server {
    listen 80;
    server_name gustavosaiani.com www.gustavosaiani.com;
    return 301 https://gustavosaiani.com$request_uri;
}

server {
    listen 443 ssl;
    server_name gustavosaiani.com www.gustavosaiani.com;

    root /var/www/gustavosaiani.com/public_html;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/gustavosaiani.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gustavosaiani.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_log /var/log/nginx/gustavosaiani.com-error.log;
}
