server {
    listen 80;
    server_name pequeno-principe-carioca.gustavosaiani.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name pequeno-principe-carioca.gustavosaiani.com;

    root /var/www/pequeno-principe-carioca.gustavosaiani.com;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/pequeno-principe-carioca.gustavosaiani.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pequeno-principe-carioca.gustavosaiani.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ $uri.html $uri/index.html =404;
    }

    error_log /var/log/nginx/pequeno-principe-carioca.gustavosaiani.com-error.log;
    access_log /var/log/nginx/pequeno-principe-carioca.gustavosaiani.com-access.log;
}
