# Generated by Django 5.1.6 on 2026-05-19 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=40, null=True
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("tab", models.CharField(blank=True, default="", max_length=20)),
                ("locale", models.CharField(blank=True, default="", max_length=5)),
                ("question", models.TextField()),
                ("classification", models.CharField(max_length=16)),
                ("model", models.CharField(blank=True, default="", max_length=40)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("latency_ms", models.IntegerField(default=0)),
                ("status", models.CharField(default="ok", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="assistant_l_user_id_834405_idx",
                    ),
                    models.Index(
                        fields=["ip_hash", "created_at"],
                        name="assistant_l_ip_hash_4d9848_idx",
                    ),
                    models.Index(
                        fields=["ticker", "created_at"],
                        name="assistant_l_ticker_3824e5_idx",
                    ),
                ],
            },
        ),
    ]
