# Generated by Django 5.1.6 on 2026-07-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmquery",
            name="feature",
            field=models.CharField(
                choices=[
                    ("ask", "Ask about a company"),
                    ("screen", "Screen companies by filters"),
                ],
                default="ask",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="llmquery",
            name="interpreted_filters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="llmquery",
            name="ticker",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
