# Generated by Django 5.1.6 on 2026-08-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_llmquery_feature_llmquery_interpreted_filters_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(db_index=True, max_length=64)),
                ("tool_name", models.CharField(blank=True, default="", max_length=64)),
                (
                    "client_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "client_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "protocol_version",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("ip_hash", models.CharField(db_index=True, max_length=64)),
                ("failed", models.BooleanField(default=False)),
                ("rate_limited", models.BooleanField(default=False)),
                ("latency_ms", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "method"],
                        name="assistant_m_timesta_94c24d_idx",
                    ),
                    models.Index(
                        fields=["timestamp", "tool_name"],
                        name="assistant_m_timesta_4b6b54_idx",
                    ),
                    models.Index(
                        fields=["timestamp", "ip_hash"],
                        name="assistant_m_timesta_f97b51_idx",
                    ),
                ],
            },
        ),
    ]
