# Generated by Django 6.0.3 on 2026-05-08 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Spond",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                ("ticker", models.CharField(blank=True, default="", max_length=10)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="social.spond",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpondLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="social.spond",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpondMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentioned_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentioned_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handle_mentions",
                        to="social.spond",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpondTickerMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticker_mentions",
                        to="social.spond",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actor"], name="social_bloc_actor_i_a76aaf_idx"
                    ),
                    models.Index(
                        fields=["target"], name="social_bloc_target__822489_idx"
                    ),
                ],
                "unique_together": {("actor", "target")},
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted")],
                        default="accepted",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "followee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["followee", "state"],
                        name="social_foll_followe_703e5d_idx",
                    ),
                    models.Index(
                        fields=["follower", "state"],
                        name="social_foll_followe_25603b_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follower", models.F("followee")), _negated=True
                        ),
                        name="follow_no_self",
                    )
                ],
                "unique_together": {("follower", "followee")},
            },
        ),
        migrations.CreateModel(
            name="Mute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muted_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actor"], name="social_mute_actor_i_3718ab_idx"
                    )
                ],
                "unique_together": {("actor", "target")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("followed", "Followed"),
                            ("follow_requested", "Follow requested"),
                            ("replied", "Replied"),
                            ("mentioned", "Mentioned"),
                            ("liked", "Liked"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_object_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emitted_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="social_noti_recipie_54eb87_idx",
                    ),
                    models.Index(
                        condition=models.Q(("read_at__isnull", True)),
                        fields=["recipient", "-created_at"],
                        name="notif_unread_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="spond",
            index=models.Index(
                fields=["author", "-created_at"], name="social_spon_author__b09401_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spond",
            index=models.Index(
                fields=["ticker", "-created_at"], name="social_spon_ticker_959e3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spond",
            index=models.Index(
                fields=["parent", "created_at"], name="social_spon_parent__0d9946_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spond",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["-created_at"],
                name="spond_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spondlike",
            index=models.Index(
                fields=["spond", "-created_at"], name="social_spon_spond_i_af2aba_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spondlike",
            unique_together={("user", "spond")},
        ),
        migrations.AddIndex(
            model_name="spondmention",
            index=models.Index(
                fields=["mentioned_user", "-created_at"],
                name="social_spon_mention_778884_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spondmention",
            unique_together={("spond", "mentioned_user")},
        ),
        migrations.AddIndex(
            model_name="spondtickermention",
            index=models.Index(
                fields=["ticker", "-created_at"], name="social_spon_ticker_1cbd77_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spondtickermention",
            unique_together={("spond", "ticker")},
        ),
    ]
